workflows:
  my-custom-workflow:
    name: Build Shahab Game
    max_build_duration: 10
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
    scripts:
      - name: Build Single File APK
        script: |
          mkdir -p android/app
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
